jobs:  
  - name: nginx-manifest-trace_copy
    type: manifest
    steps:
      - IN: nginx-image-trace_copy
      - IN: trigger-trace_copy

  - name: ddc-deploy-trace_copy
    type: deploy
    steps:
      - IN: nginx-manifest-trace_copy
      - IN: ddc-cluster-trace_copy
      - IN: params-trace_copy
      - TASK: managed
