jobs:
  - name: build-nexec
    type: runSh
    steps:
      - IN: nexec-repo
      - IN: microbase-img
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/nexec-repo/gitRepo/build.sh
    on_success:
      - script: echo 'success job :)'
    on_failure:
      - script: echo 'Failed job :('
