jobs:
  - name: nginx-manifest-1
    type: manifest
    steps:
      - IN: nginx-image-prod83

  - name: runSh-Job-1
    type: runSh
    steps:
      - IN: runSh-Job-2
      - IN: nginx-image-4
      - TASK:
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
  - name: runSh-Job-2
    type: runSh
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
  - name: runSh-Job-3
    type: runSh
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
