jobs:
  - name: manifest-1
    type: manifest
    steps:
      - IN: nginx-image

  - name: manifest-2
    type: manifest
    steps:
      - IN: manifest-1

#  - name: ecs-deploy-2
#    type: deploy
#    steps:
#      - IN: nginx-manifest-2
#      - IN: ecs-cluster-2
#      - TASK: managed
#        deployMethod: upgrade
