jobs:
  - name: runSh-Job2
    type: runSh
    steps:
      - IN: serial-trigger2
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 300
    on_success:
      - script: echo "successfully completed"
      
  - name: nginx-manifest-2
    type: manifest
    steps:
      - IN: nginx-image-prod82
      - IN: runSh-Job2
