jobs:
  - name: manifest-dcl-general-1
    type: manifest
    steps:
      - IN: image-dcl-general-1
      - TASK: managed
      - IN: trigger-dcl-general

  - name: manifest-dcl-general-2
    type: manifest
    steps:
      - IN: image-dcl-general-2
      - IN: replicas-dcl-general
      - TASK: managed
      - IN: trigger-dcl-general

  - name: deploy-dcl-general
    type: deploy
    steps:
      - IN: manifest-dcl-general-1
      - IN: manifest-dcl-general-2
      - IN: cluster-dcl-general
      - TASK: managed
