jobs:
  - name: runSh-Job2
    type: runSh
    steps:
      - IN: serial-trigger2
      - TASK:
        - script: echo "sudo apt-get install tree" && sudo apt-get install tree
        - script: echo "tree -F IN" && tree -F IN
        - script: echo "sleep 30" && sleep 30
        - script: echo "true1"
        - script: echo "sleep 2" && sleep 2
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
  - name: nginx-manifest-2
    type: manifest
    steps:
      - IN: nginx-image-prod82
      - IN: runSh-Job2
