jobs:
  - name: nginx-manifest-9
    type: manifest
    steps:
      - IN: nginx-image-9

  - name: ecs-deploy
    type: deploy
    steps:
      - IN: nginx-manifest-9
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: blueGreen
