jobs:
  - name: nginx-manifest-9
    type: manifest
    steps:
      - IN: nginx-image-9
      - IN: replicas-resource

  - name: nginx-manifest-10
    type: manifest
    steps:
      - IN: nginx-image-10

  - name: ecs-deploy
    type: deploy
    steps:
      - IN: nginx-manifest-9
      - IN: nginx-manifest-10
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: replace
