jobs:
  - name: runSh-Job-1
    type: runSh
    steps:
      - TASK:
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
  - name: runSh-Job-2
    type: runSh
    steps:
      - IN: runSh-Job-1
      - TASK:
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
  - name: runSh-Job-3
    type: runSh
    steps:
      - TASK:
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"

#  - name: manifest-job
#    type: manifest
