jobs:  
  - name: nginx-manifest-trace
    type: manifest
    steps:
      - IN: nginx-image-trace

  - name: ddc-deploy-trace
    type: deploy
    steps:
      - IN: nginx-manifest-trace
      - IN: ddc-cluster-trace
      - TASK: managed

  - name: runSh-trace
    type: runSh
    steps:
      - IN: nginx-image-trace
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: sample_java_runCI 
