jobs:
  - name: --dasdas_saf.asfaadadssdafaf.atom.git.git
    type: manifest
    steps:
      - IN: nginx-image

  - name: dasdas_saf.as.gittt
    type: manifest
    steps:
      - IN: nginx-image

  - name: dasdas_saf.as faadadssda
    type: manifest
    steps:
      - IN: nginx-image
      
  - name: dasdas_saf.asfaad.atomadssda
    type: manifest
    steps:
      - IN: nginx-image

#  - name: ecs-deploy-2
#    type: deploy
#    steps:
#      - IN: nginx-manifest-2
#      - IN: ecs-cluster-2
#      - TASK: managed
#        deployMethod: upgrade
