jobs:
  - name: printenvs-runSh
    type: runSh
    steps:
      - IN: node-integration
      - IN: slack-integration
      - IN: keyValuePair-integration
      - TASK:
        - script: echo 'true'
        - script: printenv 
