jobs:
  - name: nginx-manifest-dcl
    type: manifest
    steps:
      - IN: nginx-image-dcl
      - TASK: managed

  - name: dcl-deploy
    type: deploy
    steps:
      - IN: nginx-manifest-dcl
      - IN: dcl-cluster-dcl
      - TASK: managed
