jobs:
  - name: runSh-Job3
    type: runSh
    steps:
      - IN: serial-trigger3
      - TASK:
        - script: echo "sudo apt-get install tree" && sudo apt-get install tree
        - script: echo "tree -F IN" && tree -F IN
        - script: echo "sleep 300" && sleep 300
        - script: echo "true1"
        - script: echo "sleep 30" && sleep 30
        - script: echo "true2"
    on_success:
      - script: echo "successfully completed"
      
  - name: nginx-manifest-3
    type: manifest
    steps:
      - IN: nginx-image-prod83
      - IN: runSh-Job3
