jobs:
  - name: runSh-job
    type: runSh
    steps:
      - TASK:
        - script: printenv
    on_start:
      - NOTIFY: irc-resource
    on_success:
      - NOTIFY: irc-resource
    on_failure:
      - NOTIFY: irc-resource
    always:
      - NOTIFY: irc-resource
