jobs:
  - name: jenkins-job
    type: jenkinsJob
    integration: "jenkins-subint"
    pointer:
      sourceName: "test-proj"  # This is the job name on Jenk
    steps:
      - OUT: "nginx-image"

  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image
