jobs:  
  - name: nginx-manifest-trace_copy
    type: manifest
    steps:
      - IN: nginx-image-trace_copy
      - IN: trigger-trace_copy

  - name: ddc-deploy-trace_copy
    type: deploy
    steps:
      - IN: nginx-manifest-trace_copy
      - IN: ddc-cluster-trace_copy
      - IN: params-trace_copy
      - TASK: managed

  - name: runSh-trace_copy
    type: runSh
    steps:
      - IN: sample_java-gitRepo_copy
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: runSh-trace_copy
      - OUT: nginx-image-trace
