jobs:
  - name: printenvs-runSh
    type: runSh
    steps:
      - IN: node-integration
      - IN: slack-integration
      - IN: keyValuePair-integration
      - TASK:
        - script: printenv 
        - script: echo && echo && echo
        - script: cat $NODEINTEGRATION_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $NODEINTEGRATION_PATH/integration.json
        - script: echo && echo && echo
        - script: cat $KEYVALUEPAIRINTEGRATION_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $KEYVALUEPAIRINTEGRATION_PATH/integration.json  
        - script: echo && echo && echo
        - script: cat $SLACKINTEGRATION_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $SLACKINTEGRATION_PATH/integration.json
