jobs:
  - name: runSh-Job2
    type: runSh
    steps:
      - IN: serial-trigger2
      - TASK:
        - script: for NUM in `seq 1 1 30000`; do echo $NUM; done
    on_success:
      - script: echo "successfully completed"
      
  - name: nginx-manifest-2
    type: manifest
    steps:
      - IN: nginx-image-prod82
      - IN: runSh-Job2
