jobs:
  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image

  - name: runCI-manifest
    type: manifest
    steps:
      - IN: pipelines_runCI

  - name: runCI-job
    type: runCI
    steps:
      - IN: pipelines_runCI
      - OUT: nginx-image
