jobs:
  - name: runSh-job
    type: runSh
    steps:
      - IN: node-subint
      - TASK:
        - script: printenv 
        - script: echo && echo && echo
        - script: cat $NODESUBINT_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $NODESUBINT_PATH/integration.json
