jobs:
  - name: runSh-job
    type: runSh
    steps:
      - TASK:
        - script: printenv 
        - script: echo && echo && echo
        - script: cat $NODESUBINT_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $NODESUBINT_PATH/integration.json
    on_start:
      - NOTIFY: irc-resource
