jobs:
  - name: nginx-manifest-3
    type: manifest
    steps:
      - IN: nginx-image
      
  - name: nginx-manifest-4
    type: manifest
    steps:
      - IN: nginx-manifest-3

      
  - name: nginx-manifest-5
    type: manifest
    steps:
      - IN: nginx-manifest-4
