jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-resource

  - name: deploy-job
    type: deploy
    steps:
      - IN: manifest-job
      - IN: ecs-resource
      - TASK: managed
        deployMethod: upgrade
