jobs:
  - name: nginx-manifest-2
    type: manifest
    steps:
      - IN: nginx-image

  - name: ecs-deploy-2
    type: deploy
    steps:
      - IN: nginx-manifest
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: blueGreen
