jobs:
  - name: --dasdas_saf.asfaadadssdafaf.atom.atom.atom.git.git.git
    type: manifest
    steps:
      - IN: nginx-image

  - name: dasdas_saf.as  faadadssdaf#121^^&a
    type: manifest
    steps:
      - IN: nginx-image

#  - name: ecs-deploy-2
#    type: deploy
#    steps:
#      - IN: nginx-manifest-2
#      - IN: ecs-cluster-2
#      - TASK: managed
#        deployMethod: upgrade
