jobs:
  - name: nginx-manifest-2
    type: manifest
    steps:
      - IN: nginx-image-2

#  - name: ecs-deploy-2
#    type: deploy
#    steps:
#      - IN: nginx-manifest-2
#      - IN: ecs-cluster-2
#      - TASK: managed
#        deployMethod: upgrade
