jobs:
  - name: runSh-Job
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 300
    on_success:
      - script: echo "successfully completed"

  - name: sample_java_runCI
    type: runCI
    steps:
      - OUT: nginx-image

  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image
